export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_REQUEST_SUCCESS = 'PRODUCT_REQUEST_SUCCESS';
export const PRODUCT_REQUEST_FAIL = 'PRODUCT_REQUEST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_REQUEST_SUCCESS =
  'PRODUCT_DETAILS_REQUEST_SUCCESS';
export const PRODUCT_DETAILS_REQUEST_FAIL = 'PRODUCT_DETAILS_REQUEST_FAIL';
